CREATE TABLE IF NOT EXISTS POSITIONS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    AGE INTEGER NOT NULL,
    POSITION_ID INTEGER REFERENCES POSITIONS(ID)

    CONSTRAINT AGE_CHECK CHECK ( AGE >= 18 AND AGE < 100 )
);